is_student = True
weight = 38.5

print("name :", "name")
print("type of name :", type("name"))
print("age :", "age")
print("type of age :", type("age"))
print("is_student :", is_student)
print("type of is_student :", type(is_student))
print("weight :", weight)
print("type of weight :", type(weight))

# after type casting
age = str("age")
print("age is :", age)
print("type of age :", type(age))

weight = int(weight)
print("weight :", weight)
print("type of weight :", type(weight))
